# Generated by Django 5.2.4 on 2026-01-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'about', 'faq'", max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, help_text='HTML allowed (or plain text if you prefer).')),
                ('template_name', models.CharField(choices=[('core/page.html', 'Standard Page'), ('core/home.html', 'Home Page')], default='core/page.html', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('nav_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cta_enabled', models.BooleanField(default=False)),
                ('cta_heading', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=300)),
                ('cta_button_text', models.CharField(blank=True, max_length=100)),
                ('cta_button_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['nav_order', 'title'],
            },
        ),
    ]
