# Generated by Django 5.2.4 on 2026-01-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit_type', models.CharField(choices=[('CHARACTERS', 'Characters'), ('BATTLELINE', 'Battleline'), ('DEDICATED_TRANSPORT', 'Dedicated Transport'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('movement', models.DecimalField(decimal_places=1, help_text='Inches (e.g. 6.0)', max_digits=4)),
                ('toughness', models.PositiveSmallIntegerField()),
                ('save', models.PositiveSmallIntegerField(help_text='Armour save as a number (e.g. 3 for 3+)')),
                ('wounds', models.PositiveSmallIntegerField()),
                ('leadership', models.PositiveSmallIntegerField(help_text='Leadership as a number (e.g. 6 for 6+)')),
                ('objective_control', models.PositiveSmallIntegerField()),
                ('points_cost', models.PositiveIntegerField(help_text='Points per unit (or per model if you prefer—just be consistent).')),
                ('invulnerable_save', models.PositiveSmallIntegerField(blank=True, help_text='Invuln save as a number (e.g. 4 for 4+). Leave blank if none.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='factions.faction')),
            ],
            options={
                'ordering': ['faction__name', 'unit_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('faction', 'name'), name='uniq_unit_per_faction_name')],
            },
        ),
    ]
