# Generated by Django 5.2.4 on 2026-01-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='save',
            new_name='armour_save',
        ),
    ]
