# Generated by Django 5.2.4 on 2026-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_save_unit_armour_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='movement',
            field=models.PositiveIntegerField(help_text='Inches (e.g. 6.0)'),
        ),
    ]
